language: go
go:
  - 1.12.x
  - 1.13.x
before_install:
  - sudo apt-get -qq update
before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - go get -u -v github.com/karalabe/xgo
  - go get -u -v github.com/tosone/release2github
script:
  - travis_wait 20 make lint
  - make
deploy:
  provider: script
  script: make release && release2github create
  on:
    tags: true
