language: go
go:
  - 1.15.x
before_install:
  - sudo apt-get -qq update
before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.32.2
  - go install github.com/tosone/release@master
script:
  - go mod download
  - make lint
  - make
deploy:
  provider: script
  script: make release && release create
  on:
    tags: true
