version: "{build}"

clone_folder: c:\gopath\src\github.com\EffDataAly\GithubTraveler

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.10.1

init:
  - git config --global core.autocrlf input

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=c:\go\bin;c:\gopath\bin;c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%Path%
  - go version
  - go env
  - go get -u -v gopkg.in/alecthomas/gometalinter.v2
  - gometalinter.v2 --install
  - go get -u -v github.com/GoASTScanner/gas/cmd/gas/...
  - go get -u -v github.com/client9/misspell/cmd/misspell
  - copy c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\mingw32-make.exe c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\make.exe
  - copy c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\x86_64-w64-mingw32-gcc.exe c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\gcc.exe
  - make --version

build_script:
  - make lint
  - make
