AccessToken: c77d41f2027f009d0cb088068e86d6465c3ddaf0 # access token
Crawler:
  Entrance: tosone # crawler entrance that one of github user
  Timeout: 10 # request github timeout
  Debug: true # debug all the request verbose info
  ItemOutDate: 24 # Item that request another time (h)
  WaitDataReady: 10 # Wait for data is ready for handle (s)
  Verbose: true # output request info to database
  UniReqTimeout: 3600 # Unique request timeout
Database:
  Engine: sqlite3 # DB type
  Path: crawler.db # database path
  Username: github_traveler
  Password: crawler
  Host: database
  Port: 3306
  Database: traveler_db